apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1 # รัน Pod พร้อมกัน 1 ตัว
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-volume
          mountPath: /var/lib/jenkins/data
        resources: # กำหนดการใช้ Resource (วิศวกรที่ดีต้องใส่เสมอ)
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: jenkins-volume
        persistentVolumeClaim:
          claimName: jenkins-volume-claim # ต้องตรงกับชื่อ PVC ที่เราสร้างไว้ใน jenkins-pvc.yaml (PVC)